# cargo-deny configuration for Ghost_Monkey
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
all-features = true
exclude-dev = true

[licenses]
unused-allowed-license = "allow"
# Allow common open source licenses used in the Rust ecosystem
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
]
include-dev = true

# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = 'deny'
deny = [
    { crate = "git2", use-instead = "gix" },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    "libssh2-sys",
    { crate = "cmake", use-instead = "cc" },
    { crate = "windows", reason = "bloated and unnecessary", use-instead = "ideally inline bindings, practically, windows-sys" },
]
skip = []
skip-tree = [
    { crate = "windows-sys", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
]


[advisories]
yanked = "deny"
unmaintained = "workspace"
ignore = []

[sources]
# Allow crates from crates.io
unknown-registry = "deny"
unknown-git = "deny"
