# cargo-deny configuration for Ghost_Monkey
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
all-features = true
exclude-dev = true

[licenses]
unused-allowed-license = "allow"
# Allow common open source licenses used in the Rust ecosystem
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    # Allow ring's OpenSSL license
    "OpenSSL",
]
include-dev = true

# Confidence threshold for license detection
confidence-threshold = 0.8

# Whitelist specific crates with license issues
[[licenses.clarify]]
name = "ring"
version = "0.16.20"
expression = "OpenSSL"
license-files = []

[bans]
# TEMPORARY: Relaxed configuration while network-protocol PR is pending
# This addresses duplicate dependency versions caused by network-protocol's
# transitive dependencies. Once the PR is merged and released, these
# restrictions can be re-enabled.
multiple-versions = "allow"
wildcards = 'allow'
deny = []
skip = []
skip-tree = []


[advisories]
yanked = "deny"
unmaintained = "workspace"
# Temporarily ignore advisories with pending fixes
ignore = [
    # TEMPORARY: Whitelisted pending PR to fix ring vulnerability
    "RUSTSEC-2025-0009", # ring AES functions panic on overflow checking
]

[sources]
# Allow crates from crates.io
unknown-registry = "warn"
unknown-git = "warn"
