site_name: Ghost_Monkey
site_description: Educational UNIX backdoor written in Nim for authorized penetration testing and OSCP preparation
site_url: https://unclesp1d3r.github.io/ghost_monkey
repo_url: https://github.com/unclesp1d3r/ghost_monkey
repo_name: unclesp1d3r/ghost_monkey

theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - search.highlight
        - search.suggest
        - content.code.copy
        - content.code.annotate

nav:
    - Home: index.md

plugins:
    - search
    - git-revision-date-localized:
          enable_creation_date: true

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.snippets
    - pymdownx.emoji:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: pymdownx.superfences.fence_code_format
    - tables
    - toc:
          permalink: true
