[book]
title = "Ghost_Monkey: Educational Backdoor Implementation Guide"
authors = ["Ghost_Monkey Contributors"]
description = "A comprehensive guide to understanding and implementing secure network protocols for educational penetration testing"
src = "src"
language = "en"

[build]
build-dir = "book"

[output.html]
theme = "src/theme"
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
additional-css = ["src/theme/custom.css"]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2"
