name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/copilot-setup-steps.yml
    pull_request:
        paths:
            - .github/workflows/copilot-setup-steps.yml

jobs:
    # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
    copilot-setup-steps:
        runs-on: ubuntu-latest

        # Set the permissions to the lowest permissions possible needed for your steps.
        # Copilot will be given its own token for its operations.
        permissions:
            # If you want to clone the repository as part of your setup steps, for example to
            # install dependencies, you'll need the `contents: read` permission. If you don't
            # clone the repository in your setup steps, Copilot will do this for you
            # automatically after the steps complete.
            contents: read

        # You can define any steps you want, and they will run before the agent starts.
        # If you do not check out your code, Copilot will do this for you.
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - uses: dtolnay/rust-toolchain@1.90

            - name: Install just task runner
              uses: taiki-e/install-action@v2
              with:
                  tool: just

            - name: Set up Python for pre-commit
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Install cargo tools
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-nextest,cargo-llvm-cov,cargo-audit,cargo-deny,cargo-dist,mdbook

            - name: Install mdbook plugins
              uses: taiki-e/install-action@v2
              with:
                  tool: mdbook-admonish,mdbook-mermaid,mdbook-linkcheck,mdbook-toc,mdbook-open-on-gh,mdbook-tabs,mdbook-i18n-helpers

            - name: Run just install
              run: |
                  just install-tools

            - name: Setup summary
              run: |
                  echo "✅ Ghost_Monkey development environment setup complete!"
                  echo ""
                  echo "Available tools:"
                  echo "  - Rust toolchain: $(rustc --version)"
                  echo "  - Cargo: $(cargo --version)"
                  echo "  - just: $(just --version)"
                  echo "  - cargo-nextest: $(cargo nextest --version)"
                  echo "  - cargo-llvm-cov: $(cargo llvm-cov --version)"
                  echo "  - cargo-audit: $(cargo audit --version)"
                  echo "  - cargo-deny: $(cargo deny --version)"
                  echo "  - cargo-dist: $(cargo dist --version)"
