name: Security

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.90

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-outdated,cargo-dist

      - uses: EmbarkStudios/cargo-deny-action@v1

      - name: Run cargo outdated
        run: cargo outdated --depth=1 --exit-code=1

      - name: Run cargo dist check
        run: cargo dist check
